add_lunch_combo cyanogen_kyros7015gb-eng
add_lunch_combo cyanogen_m701gb-eng
add_lunch_combo cyanogen_m701gb_8k-eng
add_lunch_combo cyanogen_miscroll_8k-eng
add_lunch_combo cyanogen_p7sgb_8k-eng
add_lunch_combo cyanogen_scroll7c_8k-eng
